# 
repo: "https://github.com/e-gov/eIDAS-Connector"
baseurl: "https://e-gov.github.io/eIDAS-Connector"
viimatiMuudetud: '12.02.2018'

defaults:
  -
    scope:
      path: "" # Kõik failid
    values:
      layout: "Times"

