# 
repo: "https://github.com/e-gov/eIDAS-Node"
baseurl: "https://e-gov.github.io/eIDAS-Node"
viimatiMuudetud: '30.10.2020'

defaults:
  -
    scope:
      path: "" # Kõik failid
    values:
      layout: "Times"

